name: postsubmit
on:
  workflow_call: {}
  workflow_dispatch:
jobs:
  postsubmit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: hydrate-goproxy
      run: |
        mkdir -p hydrate-goproxy
        cd hydrate-goproxy
        go mod init hydrate-goproxy
        go get github.com/aws-controllers-k8s/${{ github.event.repository.name }}@${{ github.sha }}
